--- # global parameters

platformVersion : 0.3.0
workDirectory : /home/vss
domain : nimblebook.com
domainId : NB

cassandraKeySpace : nimblebook
storageKeySpace: vs
resourceKeySpace: resources
searchKeySpace: nimble

cassandraCqlPort : 9042
cassandraHosts:
    - 10.3.0.206
    - 10.3.0.125
    - 10.3.0.205

httpClientPool: 50

asyncHttpClient:
    enabled: false

mqConfiguration : 
    discoveryURI : 
    networkTTL : 2
    #
    # failover = true to randomly select a network MQ node
    # Otherwise fallback to "master-slave" discovery protocol
    #
    failover : false
    #
    # Optional broker-to-broker security:
    # activemq.xml should have configured <plugins><simpleAuthenticationPlugin>
    #
    username : user
    password : password
    #
    port : 61617
    directoryOffset : nimble-mq
